name: Atualizar XP Diario
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install firebase-admin node-fetch

      - name: Rodar script de atualização
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/atualizar-xp.js
